# Generated by Django 4.1.5 on 2023-04-22 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(default='', max_length=256, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Число закаказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone_number',
            field=models.CharField(max_length=12, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_second_name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая стоимость'),
        ),
    ]
