# Generated by Django 4.1.5 on 2023-04-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_orderitem_options_remove_order_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_names',
            field=models.TextField(blank=True, verbose_name='Названия товаров'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_quantities',
            field=models.TextField(blank=True, verbose_name='Количество товаров'),
        ),
    ]
