# Generated by Django 4.1.5 on 2023-04-29 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_product_names_order_product_quantities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_names',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_quantities',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
