# Generated by Django 4.1.5 on 2023-04-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.CharField(max_length=250),
        ),
    ]
