# Generated by Django 4.1.5 on 2023-05-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_order_design_photo_alter_order_customer_tg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='design_photo',
            field=models.ImageField(blank=True, upload_to='design_photos/%Y/%m/%d', verbose_name='Дизайн торта/ Фото'),
        ),
    ]
